# frozen_string_literal: true

module Chronopost
  module Labels
    class Create
      module Defaults
        PARAMS = {
          header_value: {
            account_number: nil,
            id_emit: 'CHRFR',
            sub_account: 0,
          },
          shipper: {
            shipper_name: nil,
            shipper_name_additional: nil,
            shipper_civility: nil,
            shipper_contact_name: nil,
            shipper_address: nil,
            shipper_address_additional: nil,
            shipper_postal_code: nil,
            shipper_city: nil,
            shipper_country_code: nil,
            shipper_country_name: nil,
            shipper_email: nil,
            shipper_phone: nil,
            shipper_mobile: nil,
            shipper_pre_alert: 0,
          },
          customer: {
            customer_name: nil,
            customer_name_additional: nil,
            customer_civility: nil,
            customer_contact_name: nil,
            customer_address: nil,
            customer_address_additional: nil,
            customer_postal_code: nil,
            customer_city: nil,
            customer_country_code: nil,
            customer_country_name: nil,
            customer_email: nil,
            customer_phone: nil,
            customer_mobile: nil,
            customer_pre_alert: 0,
            print_as_sender: 'N',
          },
          recipient: {
            recipient_name: nil,
            recipient_name_additional: nil,
            recipient_civility: nil,
            recipient_contact_name: nil,
            recipient_address: nil,
            recipient_address_additional: nil,
            recipient_postal_code: nil,
            recipient_city: nil,
            recipient_country_code: nil,
            recipient_country_name: nil,
            recipient_email: nil,
            recipient_phone: nil,
            recipient_mobile: nil,
            recipient_pre_alert: 0,
          },
          reference: {
            customer_skybill_number: nil,
            pcard_transaction_number: nil,
            recipient_reference: nil,
            shipper_reference: nil,
          },
          skybill: {
            bulk_number: nil,
            skybill_rank: nil,
            master_skybill_number: nil,
            cod_currency: 'EUR',
            cod_price: nil,
            customs_currency: 'EUR',
            customs_price: 0,
            insurance_currency: 'EUR',
            insurance_price: 0.0,
            port_currency: nil,
            port_price: 0.0,
            evt_code: 'DC',
            object_type: 'MAR',
            product_code: 86,
            service: 0,
            shipping_date: nil,
            shipping_hour: nil,
            weight: nil,
            weight_unit: 'KGM',
            height: nil,
            length: nil,
            width: nil,
            content1: nil,
            content2: nil,
            content3: nil,
            content4: nil,
            content5: nil,
            latitude: nil,
            longitude: nil,
            quality: nil,
            source: nil,
            as: nil,
            to_the_order_of: nil,
          },
          skybill_params: {
            duplicate: 'N',
            mode: 'PPR',
            with_reservation: 1,
          },
          password: nil,
          send_label_to_sender: 2,
          number_of_parcels: 1,
          version: 2.0,
          multiparcel: 'N',
        }.freeze
      end
    end
  end
end
